# https://plugins.jenkins.io/docker-plugin/
# https://devopscube.com/docker-containers-as-build-slaves-jenkins/
version: '3.8'

services:
    jenkins:
        container_name: jenkins
        image: jenkinsci/blueocean:latest
        ports:
            - ${HOST_PORT}:8080
        volumes:
            - jenkins-data:/var/jenkins_home:rw
        networks:
            - jenkins_net
        restart: always
volumes:
    jenkins-data:
networks:
    jenkins_net: